apiVersion: v1
kind: Namespace
metadata:
  name: git
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-svc
  namespace: git
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: git-spc
  namespace: git
spec:
  provider: vault     
  secretObjects:
  - secretName: git
    type: Opaque
    data: 
    - objectName: authorized_keys
      key: authorized_keys                    
  parameters:                                 
    roleName: "${cluster_name}-git-git-svc-git"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects:  |
      - secretPath: "k8s-${cluster_name}/kubernetes-${cluster_name}-git"
        objectName: "authorized_keys"
        secretKey: "authorized_keys"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
  namespace: git
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: git
  name: git
  namespace: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      serviceAccountName: git-svc
      containers:
      - image: ${image}
        name: git
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        - name: git-pv
          mountPath: "/git/repos"
      securityContext:
        fsGroup: 1002
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "git-spc"
      - name: git-pv
        persistentVolumeClaim:
          claimName: git-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: git
  name: git
  namespace: git
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "${domain}"
spec:
  ports:
  - name: ssh
    port: 30022
    protocol: TCP
    targetPort: 22
  selector:
    app: git
  type: LoadBalancer