---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "../../../infrastructure/external-dns/"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      cluster_name: prod
      pihole_domain_filter: martin.lan