---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secret-store-csi-driver
  namespace: kube-system
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: '1.4.8'
      sourceRef:
        kind: HelmRepository
        name: secret-store-csi-driver
      interval: 5m
  releaseName: csi-secrets-store
  values:
    syncSecret:
      enabled: true