apiVersion: v1
kind: Namespace
metadata:
  name: bookstack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstack-svc
  namespace: bookstack
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bookstack-spc
  namespace: bookstack
spec:
  provider: vault     
  secretObjects:
  - secretName: mariadb
    type: Opaque
    data: 
    - objectName: database_password
      key: password
    - objectName: database_root_password
      key: root_password                     
  parameters:                                 
    roleName: "${cluster_name}-bookstack-bookstack-svc-mariadb"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects:  |
      - secretPath: "k8s-${cluster_name}/kubernetes-${cluster_name}-bookstack-mariadb"
        objectName: "database_password"
        secretKey: "password"
      - secretPath: "k8s-${cluster_name}/kubernetes-${cluster_name}-bookstack-mariadb"
        objectName: "database_root_password"
        secretKey: "root_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-bind
  name: secret-bind
  namespace: bookstack
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-bind
  template:
    metadata:
      labels:
        app: secret-bind
    spec:
      serviceAccountName: bookstack-svc
      containers:
      - image: alpine
        name: alpine
        command:
        - sleep
        - infinity
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "bookstack-spc"