apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 5m
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: '0.38.0'
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      interval: 5m
  releaseName: mariadb-operator-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mariadb-operator
      version: '0.38.0'
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      interval: 5m
  releaseName: mariadb-operator