apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookstack
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "../../../apps/bookstack/"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      cluster_name: dev
