apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: danstechjourney
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "../../../apps/danstechjourney/"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      domain: danstechjourney.com
      cluster_name: dev
      image: 'registry.registry:5000/danstechjourney' # {"$imagepolicy": "flux-system:danstechjourney:name"}
      image_tag: '1742644463' # {"$imagepolicy": "flux-system:danstechjourney:tag"}
