apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: danstechjourney
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "../../../apps/danstechjourney/"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      domain: danstechjourney.com
      cluster_name: dev
      image: 'registry-dev.martin.lan:443/danstechjourney'
      image_tag: '1743082822' # {"$imagepolicy": "flux-system:danstechjourney:tag"}
