---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: git
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "../../../apps/git_server/"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      domain: git.martin.lan
      cluster_name: prod
      image: registry.martin.lan:443/ssh:0.0.7