---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: registry
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "../../../apps/registry/"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      domain: registry.martin.lan
      cluster_name: prod